import { describe, expect, it } from 'vitest';
import { acceptEvents, evaluate, publicView, type Journey, type ClientEvent } from '../src/lib/journey';
const now=Date.parse('2026-09-16T12:00:00Z');
function journey():Journey{return {id:crypto.randomUUID(),ownerHash:'owner-secret-hash',shareHash:'share-secret-hash',ackHash:'ack-secret-hash',name:'Jamie',contactName:'Alex',destination:'Home',start:{lat:9.9816,lng:76.2999},end:{lat:9.9925,lng:76.3044},durationMinutes:1,graceSeconds:20,responseSeconds:20,demo:true,status:'ACTIVE',createdAt:new Date(now-1000).toISOString(),startedAt:new Date(now).toISOString(),expectedAt:new Date(now+60000).toISOString(),expiresAt:new Date(now+86400000).toISOString(),events:[]};}
function event(type:ClientEvent['type'],sequence=1):ClientEvent{return {id:crypto.randomUUID(),type,sequence,occurredAt:new Date(now+1000).toISOString()};}
describe('journey safety boundaries',()=>{
  it('does not escalate before the exact grace and response boundary',()=>{const j=journey();evaluate(j,now+59999);expect(j.status).toBe('ACTIVE');evaluate(j,now+60000);expect(j.status).toBe('GRACE_PERIOD');evaluate(j,now+80000);expect(j.status).toBe('CHECK_IN_DUE');evaluate(j,now+99999);expect(j.status).toBe('CHECK_IN_DUE');evaluate(j,now+100000);expect(j.status).toBe('ESCALATED');});
  it('catches up a delayed scheduler and never duplicates transitions',()=>{const j=journey();evaluate(j,now+200000);evaluate(j,now+300000);expect(j.events.map(e=>e.type)).toEqual(['ETA_MISSED','CHECK_IN_REQUESTED','ESCALATION_SENT']);});
  it('arrival detection never means safe arrival',()=>{const j=journey();acceptEvents(j,[{...event('LOCATION_RECORDED'),point:j.end,accuracy:10}],now+1000);expect(j.status).toBe('ARRIVAL_DETECTED');acceptEvents(j,[event('SAFE_CONFIRMED',2)],now+2000);expect(j.status).toBe('COMPLETED');});
  it('retains SOS when deadline evaluation runs',()=>{const j=journey();acceptEvents(j,[event('SOS_TRIGGERED')],now+1000);evaluate(j,now+200000);expect(j.status).toBe('SOS');expect(j.events).toHaveLength(1);});
  it('acknowledgement does not disable escalation or imply safety',()=>{const j=journey();evaluate(j,now+100000);j.acknowledgedAt=new Date(now+110000).toISOString();evaluate(j,now+200000);expect(j.status).toBe('ESCALATED');acceptEvents(j,[event('SAFE_CONFIRMED')],now+200000);expect(j.status).toBe('COMPLETED');});
  it('deduplicates partial retries without losing accepted events',()=>{const j=journey();const a={...event('LOCATION_RECORDED'),point:j.start};const b={...event('LOCATION_RECORDED',2),point:j.start};acceptEvents(j,[a],now+1000);const result=acceptEvents(j,[a,b],now+2000);expect(result.duplicates).toEqual([a.id]);expect(result.accepted).toEqual([b.id]);expect(j.events).toHaveLength(2);});
  it('does not reopen a completed journey from an old SOS',()=>{const j=journey();acceptEvents(j,[event('SAFE_CONFIRMED')],now+1000);const result=acceptEvents(j,[event('SOS_TRIGGERED',2)],now+2000);expect(result.rejected).toHaveLength(1);expect(j.status).toBe('COMPLETED');});
  it('accepts delayed historical locations after prioritized safe confirmation',()=>{const j=journey();acceptEvents(j,[event('SAFE_CONFIRMED',2)],now+2000);const result=acceptEvents(j,[{...event('LOCATION_RECORDED'),point:j.start}],now+3000);expect(result.accepted).toHaveLength(1);expect(j.status).toBe('COMPLETED');});
  it('rejects future timestamps and does not remove an SOS',()=>{const j=journey();j.status='SOS';const result=acceptEvents(j,[{...event('SAFE_CONFIRMED'),occurredAt:new Date(now+9999999).toISOString()}],now+2000);expect(result.rejected).toHaveLength(1);expect(j.status).toBe('SOS');});
  it('keeps credentials and contact details out of the public view',()=>{const view=publicView(journey());expect(view).not.toHaveProperty('ownerHash');expect(view).not.toHaveProperty('shareHash');expect(view).not.toHaveProperty('ackHash');expect(view).not.toHaveProperty('contactName');});
});
