import { ArrowRight, Check, MapPin, ShieldCheck, LockKeyhole } from 'lucide-react';
import { Shell } from '@/components/shell';
export default function Home(){return <Shell>
  <div className="page-heading"><div><div className="eyebrow">A LITTLE REASSURANCE GOES A LONG WAY</div><h1>Every journey.<br/><em>A little more peace of mind.</em></h1><p>Head out with confidence. Keep someone you trust<br className="desktop-only"/> close, from your first step to your safe arrival.</p></div></div>
  <section className="hero-card"><div className="hero-content"><h2>You go.<br/>We keep them<br/><span>in the loop.</span></h2><p>Share your trip, stay connected, and let your person know when you’re safely there.</p><a className="button primary" href="/create">Start a journey <ArrowRight size={18}/></a><div className="hero-footnote"><LockKeyhole size={13}/> A private link. No account needed to follow.</div></div>
  <div className="hero-art" aria-label="Illustration of a shared journey"><div className="map-grid"/><svg className="route-art" viewBox="0 0 520 420" aria-hidden="true"><path d="M-30 110 L560 110 M-30 290 L560 290 M110 -20 L110 460 M340 -20 L340 460" stroke="#fff" strokeWidth="32"/><path d="M-30 110 L560 110 M-30 290 L560 290 M110 -20 L110 460 M340 -20 L340 460" stroke="#dce4db" strokeWidth="2"/><path d="M-20 410 Q90 320 185 400 T560 355" stroke="#cee3df" strokeWidth="53" fill="none"/><path d="M115 285 L220 285 Q245 285 245 260 L245 135 Q245 110 270 110 L340 110 L340 72" stroke="#2d7152" strokeWidth="5" fill="none" strokeLinecap="round" strokeDasharray="2 10"/><circle cx="115" cy="285" r="19" fill="#2d7152" opacity=".13"/><circle cx="115" cy="285" r="8" fill="#2d7152" stroke="white" strokeWidth="4"/><circle cx="245" cy="205" r="25" fill="#2d7152" opacity=".13"/><circle cx="245" cy="205" r="12" fill="#2d7152" stroke="white" strokeWidth="5"/></svg>
    <div className="destination-tag"><MapPin size={15}/> Home <span>your destination</span></div><div className="map-label label-one">THE WAY HOME</div><div className="map-label label-two">RIVERSIDE</div>
    <div className="floating-update"><span className="avatar">J</span><div><strong>Jamie is on the way</strong><span><span className="live-dot"/> Journey shared with you</span></div><span className="mini-check"><Check size={14}/></span></div>
    <div className="floating-safe"><span><ShieldCheck size={22}/></span><div><strong>A check-in that matters</strong><p>Safe arrival, confirmed by you.</p></div></div><span className="illustration-label">ILLUSTRATIVE PREVIEW</span>
  </div></section>
  <div className="honesty-note"><ShieldCheck size={18}/><p><strong>A companion, with clear limits.</strong> Keep the app open for location tracking. This prototype does not contact emergency services, and offline alerts wait for a connection.</p></div>
  </Shell>;}
