'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowRight, Check, CheckCheck, Clock3, Copy, MapPin, Play, Radio, RefreshCw, Share2, ShieldCheck, WifiOff, AlertTriangle, X } from 'lucide-react';
import { isClosed, orderedLocations, statusLabel, type ClientEvent, type Point, type PublicJourney, type Status } from '@/lib/journey';
import { enqueue, pending, sync, type QueuedEvent } from '@/lib/offline';
import { Shell } from './shell';
const JourneyMap=dynamic(()=>import('./map'),{ssr:false,loading:()=> <div className="map-loading">Loading your map…</div>});
type ClosedView={closed:true;name:string;status:Status;completedAt:string;expiresAt:string};
const formatTime=(value?:string)=>value?new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Not started';
export function JourneyScreen({id,follower=false}:{id:string;follower?:boolean}){
  const [journey,setJourney]=useState<PublicJourney|null>(null);const [closed,setClosed]=useState<ClosedView|null>(null);const [error,setError]=useState('');const [note,setNote]=useState('');
  const [online,setOnline]=useState(true);const [serverAvailable,setServerAvailable]=useState(true);const [queue,setQueue]=useState<QueuedEvent[]>([]);const [now,setNow]=useState(Date.now);const [busy,setBusy]=useState(false);const [tracking,setTracking]=useState(false);const [hold,setHold]=useState(false);const [sharePath,setSharePath]=useState('');const [cancelOpen,setCancelOpen]=useState(false);
  const journeyRef=useRef(journey);const holdTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const gps=useRef<number|null>(null);const lastCapture=useRef(0);const refreshing=useRef(false);
  useEffect(()=>{journeyRef.current=journey;},[journey]);
  const refresh=useCallback(async()=>{
    if(refreshing.current)return;refreshing.current=true;
    try{
      if(!follower){setQueue(await pending(id));if(navigator.onLine){await sync(id);setQueue(await pending(id));}}
      const response=await fetch(follower?`/api/follow/${id}`:`/api/journeys/${id}`,{cache:'no-store'});
      const result=await response.json();if(!response.ok){if(response.status===404){setJourney(null);setError(result.error);}throw new Error(result.error);}
      if(result.closed){setClosed(result);setJourney(null);}else{setJourney(result);if(!follower)localStorage.setItem(`sj-journey-${id}`,JSON.stringify(result));}
      setServerAvailable(true);setError('');
    }catch(e){setServerAvailable(false);if(!journeyRef.current)setError(e instanceof Error?e.message:'Unable to connect.');}
    finally{refreshing.current=false;}
  },[id,follower]);
  useEffect(()=>{
    if(!follower){try{const cached=localStorage.getItem(`sj-journey-${id}`);if(cached)setJourney(JSON.parse(cached));setSharePath(localStorage.getItem(`sj-share-${id}`)||'');}catch{/* A malformed local cache can be replaced by the server. */}}
    setOnline(navigator.onLine);void refresh();const timer=setInterval(()=>{setNow(Date.now());void refresh();},3000);
    const change=()=>{setOnline(navigator.onLine);void refresh();};window.addEventListener('online',change);window.addEventListener('offline',change);
    return()=>{clearInterval(timer);window.removeEventListener('online',change);window.removeEventListener('offline',change);};
  },[refresh,id,follower]);
  const capture=useCallback(async(type:ClientEvent['type'],point?:Point,accuracy?:number)=>{
    try{await enqueue(id,{type,point,accuracy});setQueue(await pending(id));if(type==='SAFE_CONFIRMED')setNote('Check-in saved — waiting for server confirmation.');if(type==='SOS_TRIGGERED')setNote('SOS saved — waiting for connection and server confirmation.');void refresh();}
    catch{setError('This device could not save the update. Check browser storage permissions.');}
  },[id,refresh]);
  useEffect(()=>{
    if(!journey||follower||journey.demo||!journey.startedAt||isClosed(journey))return;
    if(!navigator.geolocation){setError('This browser does not support location tracking.');return;}
    gps.current=navigator.geolocation.watchPosition(position=>{
      if(Date.now()-lastCapture.current<15000)return;lastCapture.current=Date.now();setTracking(true);
      void capture('LOCATION_RECORDED',{lat:position.coords.latitude,lng:position.coords.longitude},position.coords.accuracy);
    },()=>{setTracking(false);setError('Location unavailable. Keep this page open and allow location access in browser settings.');},{enableHighAccuracy:true,maximumAge:10000,timeout:20000});
    return()=>{if(gps.current!==null)navigator.geolocation.clearWatch(gps.current);};
  },[journey?.startedAt,journey?.status,journey?.demo,follower,capture]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>()=>{if(holdTimer.current)clearTimeout(holdTimer.current);},[]);
  const points=useMemo(()=>{if(!journey)return [];return [...orderedLocations(journey).map(e=>e.point!),...queue.filter(e=>e.type==='LOCATION_RECORDED'&&e.point).sort((a,b)=>a.sequence-b.sequence).map(e=>e.point!)];},[journey,queue]);
  async function start(){setBusy(true);try{const response=await fetch(`/api/journeys/${id}/start`,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);setJourney(result);if(result.demo)await capture('LOCATION_RECORDED',result.start,10);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not start journey.');}finally{setBusy(false);}}
  async function share(){const url=new URL(sharePath,window.location.origin).href;try{if(navigator.share)await navigator.share({title:'Follow my SafeJourney',url});else{await navigator.clipboard.writeText(url);setNote('Private link copied. Send it to your trusted contact.');}}catch(e){if((e as Error).name!=='AbortError')setNote('Use the link field below to copy your private link.');}}
  async function ack(){setBusy(true);try{const ackToken=new URLSearchParams(window.location.hash.slice(1)).get('ack');if(!ackToken)throw new Error('Open the complete link shared by the traveller to acknowledge.');const response=await fetch(`/api/escalation/${ackToken}`,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);setNote('Acknowledged. Please contact the traveller to check on them.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function move(arrive=false){if(!journey)return;const count=points.length;const progress=arrive?1:Math.min(.85,count*.12);void capture('LOCATION_RECORDED',{lat:journey.start.lat+(journey.end.lat-journey.start.lat)*progress,lng:journey.start.lng+(journey.end.lng-journey.start.lng)*progress},10);}
  function holdStart(){if(holdTimer.current)return;setHold(true);holdTimer.current=setTimeout(()=>{void capture('SOS_TRIGGERED',points.at(-1));setHold(false);holdTimer.current=null;},2000);}
  function holdEnd(){if(holdTimer.current)clearTimeout(holdTimer.current);holdTimer.current=null;setHold(false);}
  if(closed)return <Shell back><div className="completion"><span className="completion-icon"><ShieldCheck size={40}/></span><div className="eyebrow">A LITTLE PEACE OF MIND</div><h1>{closed.name} arrived safely.</h1><p>Confirmed at {formatTime(closed.completedAt)}. Location sharing has ended.</p><p className="muted">This confirmation expires after 24 hours from journey creation.</p><a className="button secondary" href="/">Back to SafeJourney <ArrowRight size={16}/></a></div></Shell>;
  if(!journey)return <Shell back><div className="completion"><ShieldCheck size={36}/><h1>{error?'Journey unavailable':'Opening your journey…'}</h1><p role={error?'alert':undefined}>{error||'Connecting securely to the journey.'}</p><a className="button secondary" href="/">Back to overview</a></div></Shell>;
  const last=orderedLocations(journey).at(-1);const age=last?Math.max(0,Math.floor((now-Date.parse(last.occurredAt))/1000)):null;const stale=age===null||age>120;const alert=['SOS','ESCALATED'].includes(journey.status);const ended=isClosed(journey);const offline=!online||!serverAvailable;
  const minutes=journey.expectedAt?Math.ceil((Date.parse(journey.expectedAt)-now)/60000):journey.durationMinutes;
  const state=journey.status;
  return <Shell active="journey" back><div className="journey-heading"><div><div className="eyebrow">{follower?`HERE FOR ${journey.name.toUpperCase()}`:'YOUR JOURNEY, TOGETHER'}</div><h1>{ended?'Home, with peace of mind.':follower?`${journey.name}’s journey`:'You’re not travelling alone.'}</h1><p>{journey.destination} <span className="text-separator">/</span> {journey.demo?'Clearly labelled demo · Simulated locations':'Keep this page open while travelling'}</p></div><span className={`status-pill ${alert?'danger':ended?'':'good'}`}><span className="live-dot"/>{statusLabel[state]}</span></div>
  {error&&<div className="notice error" role="alert">{error}</div>}
  {offline&&<div className="notice offline" role="status"><WifiOff size={20}/><div><strong>{follower?'Your connection to this journey is unavailable':'Offline record active'}</strong><p>{follower?'Showing previously received information. Alerts may be delayed.':`${queue.length} update${queue.length===1?'':'s'} saved on this device. Keep the app open; uploads resume when the server is reachable.`}</p></div></div>}
  {alert&&<div className="alert-banner" role="alert"><AlertTriangle size={24}/><div><strong>{state==='SOS'?`${journey.name} requested help`:'The expected check-in was missed'}</strong><p>{journey.acknowledgedAt?`Contact acknowledged at ${formatTime(journey.acknowledgedAt)}. Safe arrival is still unconfirmed.`:'Try contacting the traveller. A missed check-in alone does not confirm danger.'}</p></div>{follower&&!journey.acknowledgedAt&&<button className="button danger-button" onClick={ack} disabled={busy}>Acknowledge alert</button>}</div>}
  {['ARRIVAL_DETECTED','CHECK_IN_DUE'].includes(state)&&!follower&&<div className="notice warm-notice"><Clock3 size={22}/><div><strong>{state==='ARRIVAL_DETECTED'?'You’re near your destination. Are you safe?':'Your check-in is due. Are you safe?'}</strong><p>Tap “I’m safe” below to confirm. Your location alone never marks you safe.</p></div></div>}
  {note&&<div className="notice status-note" role="status">{ended?'Safe arrival confirmed by the server.':state==='SOS'?'SOS received by the server. Your contact’s view shows the alert.':note}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setNote('')}><X size={15}/></button></div>}
  <div className="journey-layout"><div><div className="journey-map-card"><div className="map-card-header"><span><MapPin size={17}/> {journey.destination}</span><span className="muted">{journey.demo?'DEMO JOURNEY':'JOURNEY MAP'}</span></div><JourneyMap start={journey.start} end={journey.end} points={points}/><div className="map-stats"><div><span>AGREED ARRIVAL</span><strong>{formatTime(journey.expectedAt)}</strong></div><div><span>LAST LOCATION</span><strong>{age===null?'Waiting for update':age<60?`${age}s ago`:`${Math.floor(age/60)} min ago`}</strong></div><div><span>{follower?'RECEIVED UPDATES':'SAVED TO UPLOAD'}</span><strong>{follower?orderedLocations(journey).length:queue.length}<small> {follower?'points':'events'}</small></strong></div></div></div>
  {journey.demo&&!follower&&!ended&&state!=='DRAFT'&&<section className="demo-panel"><div><strong><Play size={15}/> Demo controls</strong><p>These create simulated location events. Sync and server checks are real.</p></div><div className="button-row"><button className="button secondary" onClick={()=>move()}>Add movement</button><button className="button secondary" onClick={()=>move(true)}>Reach destination</button><button className="button secondary" onClick={()=>void refresh()}><RefreshCw size={14}/> Retry sync</button></div><p>Test offline recovery using your browser’s Network → Offline setting, then add movement. Restore the network to sync.</p></section>}
  <section className="timeline-card"><div className="section-title"><h2>Along the way</h2><span>Journey activity</span></div><div className="timeline">{[...journey.events].filter(e=>e.type!=='LOCATION_RECORDED').sort((a,b)=>Date.parse(b.receivedAt)-Date.parse(a.receivedAt)).slice(0,7).map(e=><div className="timeline-item" key={e.id}><span className="timeline-dot"/><div><strong>{({JOURNEY_CREATED:'Your journey was created',JOURNEY_STARTED:'Journey started',ARRIVAL_DETECTED:'Near the destination — awaiting check-in',ETA_MISSED:'Expected arrival time passed',CHECK_IN_REQUESTED:'Traveller check-in requested',ESCALATION_SENT:'Missed check-in alert is active',ESCALATION_ACKNOWLEDGED:'Contact acknowledged the alert',SAFE_CONFIRMED:'Traveller confirmed safe arrival',SOS_TRIGGERED:'Traveller requested help',JOURNEY_CANCELLED:'Journey cancelled'} as Record<string,string>)[e.type]||e.type}</strong><span>{formatTime(e.receivedAt)}</span></div></div>)}</div></section></div>
  <aside className="journey-aside"><section className="summary-card"><span className="eyebrow">{follower?'THE JOURNEY AT A GLANCE':'ONE STEP AT A TIME'}</span><h2>{ended?'You made it.':state==='DRAFT'?'Ready when you are.':alert?'Time to check in.':minutes>0?`About ${minutes} min to go.`:'Arrival time has passed.'}</h2><p>{ended?'Your safe arrival has been confirmed. Location sharing has ended.':state==='DRAFT'?'Share the link with your person, then start your journey.':'Your agreed arrival stays fixed, so your contact knows when to expect a check-in.'}</p>
  <div className="health-fact"><span className={`feature-icon small ${stale?'warm':''}`}><Radio size={17}/></span><div><strong>{ended?'Sharing ended':state==='DRAFT'?'Waiting to start':stale?'No recent location updates':'Recent location received'}</strong><p>{stale?'Missing updates can have several causes. They do not mean the traveller has stopped.':`Last received by server at ${formatTime(last?.receivedAt)}.`}</p></div></div>
  {!follower&&!ended&&<><div className="action-stack">{state==='DRAFT'?<button className="button primary full" disabled={busy||offline} onClick={start}>Start journey <ArrowRight size={17}/></button>:<><button className="button primary full" disabled={queue.some(e=>e.type==='SAFE_CONFIRMED')} onClick={()=>void capture('SAFE_CONFIRMED')}><ShieldCheck size={19}/>{queue.some(e=>e.type==='SAFE_CONFIRMED')?'Safe check-in awaiting sync':'I’m safe — end journey'}</button><button className={`button sos-button full ${hold?'holding':''}`} onPointerDown={holdStart} onPointerUp={holdEnd} onPointerLeave={holdEnd} onPointerCancel={holdEnd} onBlur={holdEnd} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();holdStart();}}} onKeyUp={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();holdEnd();}}}><AlertTriangle size={17}/>{hold?'Keep holding…':'Hold 2 seconds for SOS'}</button><span className="action-help">Offline SOS waits for a connection. No emergency dispatch.</span></>}</div>{sharePath&&<div className="share-box"><button className="button secondary full" onClick={share}><Share2 size={16}/> Share private link</button><label className="link-label">Your contact’s link<input aria-label="Private contact link" readOnly value={typeof window!=='undefined'?new URL(sharePath,window.location.origin).href:sharePath} onFocus={e=>e.target.select()}/></label><a href={sharePath} target="_blank" rel="noreferrer" className="inline-link">Open contact view <ArrowRight size={13}/></a></div>}</>}
  {!follower&&state!=='DRAFT'&&!ended&&<button className="cancel-link" onClick={()=>setCancelOpen(true)}>Cancel journey & stop sharing</button>}
  {follower&&<div className="privacy-inline"><ShieldCheck size={18}/><span>This private link allows you to follow this journey. Keep it to yourself.</span></div>}
  </section>{!follower&&<div className="notice"><ShieldCheck size={18}/><span>{journey.demo?'Demo movement only. Use the controls to add points.':tracking?'Location capture active. Keep your screen awake and this page open.':'Allow location access and keep this app open for tracking.'}</span></div>}
  {queue.length>0&&<details className="queue-details"><summary>{queue.length} saved update{queue.length===1?'':'s'} <Copy size={13}/></summary>{queue.map(e=><p key={e.id}>{e.type.replaceAll('_',' ').toLowerCase()} · #{e.sequence}<br/>{e.error?<span className="error-text">Needs attention: {e.error}</span>:<span>Waiting for acknowledgement</span>}</p>)}</details>}
  <div className="reassurance"><CheckCheck size={18}/><p>Reaching the destination is a prompt.<br/><strong>A safe check-in is a promise from you.</strong></p></div></aside></div>
  {cancelOpen&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="cancel-title"><h2 id="cancel-title">End this journey?</h2><p>Cancellation stops sharing once it reaches the server. It does not tell your contact you arrived safely.</p><div className="button-row"><button className="button secondary" onClick={()=>setCancelOpen(false)}>Keep travelling</button><button className="button danger-button" onClick={()=>{void capture('JOURNEY_CANCELLED');setCancelOpen(false);setNote('Cancellation saved — waiting for server confirmation.');}}>Cancel journey</button></div></div></div>}
  </Shell>;
}
